[project]
name = "maps"
version = "0.1.0"
description = "Make and save maps."
dependencies = [
    "PyJWT",
    "flask",
    "psycopg2",
    "bcrypt",
    "pytz",
    "waitress"
]

[project.scripts]
init_db = "data.init_db:execute"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"

