[project]
name = "maps"
authors = [{name = "Sir Robin", email = "robin@camelot.uk"}]
dynamic = ["version", "description"]
dependencies = [
    "PyJWT",
    "flask",
    "psycopg2",
    "bcrypt",
    "pytz",
    "waitress",
    "click"
]

[project.scripts]
init_db = "data.init_db:execute"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
